version: '3.8'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "80:8000"
        volumes:
            - ./project:/var/www/html

    # mailer:
    #     image: schickling/mailcatcher
    #     ports: [1025, 1080]

    mysql:
        image: mysql:5.7
        container_name: mysql57
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: symfony_db
            MYSQL_USER: devuser
            MYSQL_PASS: devpass
            MYSQL_ROOT_PASSWORD: root
volumes:
  db-data: